src/lib/tictactoe_web/router.ex
defmodule TictactoeWeb.Router do
  use TictactoeWeb, :router

  alias TictactoeWeb.Plug.Session

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {TictactoeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug(Session)
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TictactoeWeb do
    pipe_through :browser

    live("/", NewPlayer)
    live("/games/new", NewGame)
    live("/games/:id/show", ShowGame)

    delete("/logout", LogoutController, :delete)

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", TictactoeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: TictactoeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

src/lib/tictactoe_web/views/layout_view.ex
defmodule TictactoeWeb.LayoutView do
  use TictactoeWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

src/lib/tictactoe_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

src/lib/tictactoe_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

src/lib/tictactoe_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= csrf_meta_tag() %>
    <title>Tic Tac Toe game in Elixir</title>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/css/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/js/app.js")}></script>
  </head>
  <body>
    <div class="flex justify-end p-5">
      <%= if @conn.private.plug_session["player_name"] do %>
        <%= link to: Routes.logout_path(@conn, :delete), method: :delete do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-gray-600" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        <% end %>
      <% end %>
    </div>
    <%= @inner_content %>
  </body>
</html>